import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import NavbarProvider from "@/context/NavbarContext";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const items = [
    {
      text: "What I doo",
      href: "whatIDoo"
    },
    {
      text: "About me",
      href: "about"
    },
    {
      text: "Experience",
      href: "experience"
    },
    {
      text: "Tools and languages",
      href: "tools"
    },
    {
      text: "Contact",
      href: "contact"
    },
  ]
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}    antialiased`}
      >
        <NavbarProvider>
          <div className="max-w-screen-sw w-full sw:px-8 items-center mx-auto my-auto">
            <Navbar items={items} />

          </div>
          
            {children}
          <Footer />
        </NavbarProvider>
      </body>
    </html>
  );
}
